# Generated by Django 5.1.2 on 2025-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('dominio', models.URLField(blank=True, max_length=255, null=True)),
                ('cor_principal', models.CharField(blank=True, max_length=7, null=True)),
                ('cor_secundaria', models.CharField(blank=True, max_length=7, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('favicon', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blog_url', models.URLField(blank=True, max_length=255, null=True)),
                ('quem_somos_url', models.URLField(blank=True, max_length=255, null=True)),
                ('endereco_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
