# Generated by Django 5.1.2 on 2025-01-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], max_length=1)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('nome_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('descricao_endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('ramo_atividade', models.CharField(blank=True, max_length=255, null=True)),
                ('senha', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('setor_trabalho', models.CharField(blank=True, choices=[('comercial', 'Comercial'), ('producao', 'Produção'), ('financeiro', 'Financeiro'), ('impressao', 'Impressão'), ('programacao', 'Programação'), ('acabamento', 'Acabamento'), ('expedicao', 'Expedição'), ('gerencia', 'Gerência')], max_length=255, null=True)),
                ('departamentos_acesso', models.JSONField(blank=True, default=list)),
                ('acesso_completo', models.BooleanField(default=False)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.loja')),
            ],
        ),
    ]
