"""
Django settings for renovagraf project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-68@_-ul!cjg$zssuid@3scz#q_4d72fc4$zma08&g$0j%e3opu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'loja',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
]

ROOT_URLCONF = 'renovagraf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Outras opções padrão
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                # Nosso context processor de loja
                'loja.context_processors.loja_context',
            ],
        },
    },
]



WSGI_APPLICATION = 'renovagraf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'renovagraf_db',  # Substitua pelo nome do banco de dados
        'USER': 'root',  # Substitua pelo seu usuário do MySQL
        'PASSWORD': 'Renova123@',  # Substitua pela sua senha do MySQL
        'HOST': 'localhost',  # Pode ser alterado se o banco de dados estiver em outro lugar
        'PORT': '3306',  # A porta padrão do MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de envio de e-mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtps.uhserver.com'  # Usando o Gmail como exemplo
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'desenvolvimento@renovagraf.com.br'  # Substitua pelo seu e-mail
EMAIL_HOST_PASSWORD = 'Amapa244'  # Substitua pela sua senha ou senha de app do Gmail
DEFAULT_FROM_EMAIL = 'Renovagraf <desenvolvimento@renovagraf.com.br>'


AUTH_USER_MODEL = 'usuarios.Usuario'

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MERCADO_PAGO_ACCESS_TOKEN = 'APP_USR-6909337064004749-110719-3cb645f0e400a1c9f093b1ae96c8e878-2082640820'


MELHOR_ENVIO_API_URL = 'https://www.melhorenvio.com.br/api/v2/me/shipment/calculate'
MELHOR_ENVIO_API_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjg4NGNjZjJjZGFjYjUxODRlMjViZTNlMWNlNTE3Y2M0OTk1NGFkYjA2ZDRlYzAyNjdiODI2NzJmNWFiNmRlYmI3NDU4MGEwNDc5MDU3NDUiLCJpYXQiOjE3MzIwNjU0NjYuMzQ5ODk3LCJuYmYiOjE3MzIwNjU0NjYuMzQ5ODk5LCJleHAiOjE3NjM2MDE0NjYuMzM2NzgxLCJzdWIiOiI5Y2JmOGFjYy0xYmM0LTRmOGItOTJiNS01NTllY2U3YTIwZDIiLCJzY29wZXMiOlsic2hpcHBpbmctY2FsY3VsYXRlIl19.F_-QxiY2OUzmproyw8fxiKX7F_cf1smu63_3eRdgSEuLlVuV9vbwNS60Hu4vJzU-jeA_PzjjvihtT8Ldl7qrCJE6T7grAsyts3Hf8Sdz6W4No_QJ_Vltw933YJjEApzGZ_4GAGBcDJNU5FkMqKBUFQemVnnLSOq9Ucm1SlB8Eg-hf4ooIYbXSAf2rR2BUDG6ah7p17U9xMTvSfiYdlzxeOKfGKUfy2qTKX4K8kBEjvmlAEPVh42bzq6tD3SlhCGoFb4yMn-BIHybiVrB-6eD94cBYXdVWWmWRZqYrZTC0UZ8Gg4wsNCB4wPVlTqoLIPwI03wwDe01mh6tPeWsvTrY_BLIKPYyTyoAzzXV33z0yj9vQgCECPJRbbrhXXik6wONXMRuy1tmDbpSMrGAkZFtOYIoJt_K5PSto60oVQ2a2S1Qk9fB0R1LCgsXQgIjvrAISHw69yYZYftWLznWOPy6I0t3LqhG4zJUc57ReMwbJHDx43sqrYoKRo0SMHPvONA6MjE4GvfSMlgkwmr4oGRtgHPGcQYn8Qvk2_lWxpVuu8sdTOwNp-0zFuSkbDlAQSILWh3sBta5brexMLqQTGmEY8Vlak3D4iry8sQYHM-yz9F2JPSxxe549WV90lxFou_wAeOEj81vyJz0TUS_auL0KHB8RAM1naXR5mF3ReMze0'


